//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoPals.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CryptoPals.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Project Gutenberg EBook of Lady Susan, by Jane Austen
        ///
        ///This eBook is for the use of anyone anywhere at no cost and with
        ///almost no restrictions whatsoever.  You may copy it, give it away or
        ///re-use it under the terms of the Project Gutenberg License included
        ///with this eBook or online at www.gutenberg.org
        ///
        ///
        ///Title: Lady Susan
        ///
        ///Author: Jane Austen
        ///
        ///Posting Date: July 27, 2008 [EBook #946]
        ///Release Date: June 1997
        ///[Last updated: June 10, 2012]
        ///
        ///Language: English
        ///
        ///
        ///*** START OF THIS PROJECT G [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string en_corpus {
            get {
                return ResourceManager.GetString("en_corpus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Project Gutenberg EBook of The Bab Ballads, by W. S. Gilbert
        ///(#3 in our series by W. S. Gilbert)
        ///
        ///Copyright laws are changing all over the world. Be sure to check the
        ///copyright laws for your country before downloading or redistributing
        ///this or any other Project Gutenberg eBook.
        ///
        ///This header should be the first thing seen when viewing this Project
        ///Gutenberg file.  Please do not remove it.  Do not change or edit the
        ///header without written permission.
        ///
        ///Please read the &quot;legal small print,&quot; and ot [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string en_corpus2 {
            get {
                return ResourceManager.GetString("en_corpus2", resourceCulture);
            }
        }
    }
}
